services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--username",
          "admin",
          "--password",
          "admin123",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: killingcammand/fleet-management-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: npm server
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_network

  worker:
    image: killingcammand/fleet-management-backend:latest
    container_name: worker
    restart: always
    command: npm worker
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_network

volumes:
  mongo_data:
  redis_data:

networks:
  backend_network:
    driver: bridge