version: "3.9"

services:

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_network
    deploy: 
      replicas: 1
      restart_policy:
        condition: on-failure
  
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  backend:
    image: killingcammand/fleetops_backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    networks:
      - backend_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  mongo_data: 
  redis_data: 

networks:
  backend_network:
   external: true